### ISSUE TITLE
commandes multiples

### ISSUE THREAD

**Issue by LudovicRAVINET** [aldaitzwild/Metis_Cooking#40]
toujours pour chipoter, car je ne suis pas sûr que ce soit un bug (mais il faut bien trouver quelque chose...): quand on passe une commande et qu'on la valide, on ne peut pas refaire une nouvelle commande (un message nous dit qu'une commande est déjà en cours). Par contre, si on se déconnecte et reconnecte immédiatement sur le même compte, on peut repasser une commande, alors que 30 secondes avant, on nous l'interdisait !

**Comment by Bachir-Ndiaye** [comment]
Re Ludovic, c'est Thomas qui a demandé cette contrainte :/. Lorsque l'utilisateur fait une commande il ne peut pas en passer une autre, autrement on était parti sur un multi-commandes :) ! Après oui faudrait faire une autre contrainte maybe : Dès que l'utilisateur a une commande il ne peut pas en prendre une autre temps que l'admin ne l'a pas validé !

**Comment by aldaitzwild** [comment]
Sauf que là le problème est différent
- je fais une commande
- Je valide
- je fais une autre commande => Erreur : on a déjà une commande en cours (OK)
- Je me déconnecte
- Je me reconnecte
- Je fais une commande => Youhou ! Ca marche (Pas OK)

On devrai pouvoir faire un nombre illimité de commande juste en se déconnectant. On pourrait dire par exemple : Une comande par jour et par user

**Comment by Bachir-Ndiaye** [comment]
Problème résolu, merci de l'avoir signalé
